.PHONY: lint test test-race bench

lint:
	@golangci-lint run --config=./devz/golangci-lint.yaml ./...

test:
	@go test ./...

test-race:
	@go test -race ./...

bench:
	@go test -run '^$$' -bench . -benchmem ./...
