name: CI


on:
  push:
    tags:
      - 'v*'
      - '**/v*'
    branches:
      - master
  workflow_dispatch:


jobs:

  check_test_build:
    name: Check, Test, Build
    uses: sudoless/actions/.github/workflows/go-ci.yaml@master
    with:
      build: false
